export const data = [
  {
    key: "1",
    name: "SR Sr Tusher",
    age: "32",
    address: "New York No. 1 Lake Park",
    Provider: "staff1",
    service: "Assessment a (BA) (0.25 Hrs)",
    pos: "School",
    tags: ["Scheduled"],
    date: "06/30/2022",
  },
  {
    key: "2",
    name: "Ms Nitu",
    age: "42",
    address: "London No. 1 Lake Park",
    Provider: "staff2",
    service: "Assessment a (BA) (0.25 Hrs)",
    pos: "Telehealth",
    tags: ["Scheduled"],
    date: "06/30/2022",
  },
  {
    key: "3",
    name: "SR Sr Tusher",
    age: "32",
    address: "Sidney No. 1 Lake Park",
    Provider: "staff1",
    service: "Assessment a (BA) (0.25 Hrs)",
    pos: "School",
    tags: ["rendered"],
    date: "06/30/2022",
  },
  {
    key: "4",
    name: "Ms Nitu",
    age: "32",
    address: "London No. 2 Lake Park",
    Provider: "staff1",
    service: "Speech service 1 speech",
    pos: "School",
    tags: ["rendered"],
    date: "06/12/2022",
  },
  {
    key: "5",
    name: "Ms Nitu",
    age: "32",
    address: "New York No. 1 Lake Park",
    Provider: "staff2",
    service: "Assessment a (BA/BCaBA)",
    pos: "Telehealth",
    tags: ["Scheduled"],
    date: "05/08/2022",
  },
  {
    key: "6",
    name: "Ms Nitu",
    age: "42",
    address: "London No. 1 Lake Park",
    Provider: "staff1",
    service: "Assessment a (BA/BCaBA)",
    pos: "School",
    tags: ["rendered"],
    date: "05/08/2022",
  },
  {
    key: "7",
    name: "Ms Nitu",
    age: "32",
    address: "Sidney No. 1 Lake Park",
    Provider: "staff2",
    service: "Assessment a (BA) (0.25 Hrs)",
    pos: "Telehealth",
    tags: ["rendered"],
    date: "05/08/2022",
  },
  {
    key: "8",
    name: "SR Sr Tusher",
    age: "32",
    address: "London No. 2 Lake Park",
    Provider: "staff1",
    service: "Speech service 1 speech",
    pos: "School",
    tags: ["rendered"],
    date: "06/30/2022",
  },
  {
    key: "9",
    name: "SR Sr Tusher",
    age: "32",
    address: "London No. 2 Lake Park",
    Provider: "staff1",
    service: "Speech service 1 speech",
    pos: "Telehealth",
    tags: ["Scheduled"],
    date: "06/12/2022",
  },
  {
    key: "10",
    name: "Ms Nitu",
    age: "32",
    address: "New York No. 1 Lake Park",
    Provider: "staff2",
    service: "Assessment a (BA/BCaBA)",
    pos: "Telehealth",
    tags: ["rendered"],
    date: "05/08/2022",
  },
  {
    key: "11",
    name: "Ms Nitu",
    age: "42",
    address: "London No. 1 Lake Park",
    Provider: "staff1",
    service: "Assessment a (BA/BCaBA)",
    pos: "Telehealth",
    tags: ["rendered"],
    date: "06/30/2022",
  },
  {
    key: "12",
    name: "SR Sr Tusher",
    age: "32",
    address: "Sidney No. 1 Lake Park",
    Provider: "staff2",
    service: "Assessment a (BA) (0.25 Hrs)",
    pos: "Telehealth",
    tags: ["rendered"],
    date: "06/12/2022",
  },
  {
    key: "147453",
    name: "Ms Nitu",
    age: "32",
    address: "London No. 2 Lake Park",
    Provider: "staff1",
    service: "Speech service 1 speech",
    pos: "School",
    tags: ["rendered"],
    date: "06/12/2022",
  },
];
